---

- name: prepare the certificate folder
  file:
    dest: "/etc/ssl/{{ inventory_hostname }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: copy over the chain file
  copy:
    content: "{{ postfix_certificate.chain }}"
    dest: "/etc/ssl/{{ inventory_hostname }}/postfix_{{ inventory_hostname }}.chain"
    owner: postfix
    group: postfix
    mode: "0664"

- name: copy over the key file
  copy:
    content: "{{ postfix_certificate.key }}"
    dest: "/etc/ssl/{{ inventory_hostname }}/postfix_{{ inventory_hostname }}.key"
    owner: postfix
    group: postfix
    mode: "0640"
